notifications:
  email: false
git:
  quiet: true
  depth: false
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
python: 3.7
os: linux
arch: amd64
install: true
addons:
  apt:
    update: true
    packages:
      - curl
      - python3-pip
      - libhsdis0-fcml
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip  install --user --upgrade docker-compose httpie
  - docker-compose version
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ~/.local/daggerok/bash-functions/master/main.bash
  - stop_any 80 1234 8080 5432
  # scala-rsocket:
  - ulimit -c unlimited
  ## gradle
  #- curl -s "https://get.sdkman.io" | bash
  #- sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  #- source "$HOME/.sdkman/bin/sdkman-init.sh"
  #- sdk use gradle 5.5-rc-2
jobs:
  include:
    - stage: test
      jdk: openjdk11
      name: rsiocket-gateway jdk11
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f rsocket-gateway clean package
        - bash $TRAVIS_BUILD_DIR/rsocket-gateway/rsocket-messages-service/target/*.jar &
        - wait_for 8080
        - http post :8000/actuator/shutdown
        - stop_any 80 8080
    - stage: test
      name: rsiocket-gateway jdk8
      script: cd $TRAVIS_BUILD_DIR && ./mvnw -f rsocket-gateway clean package
  ## fucking travis doesn't worked...
#    - stage: test
#      jdk: openjdk8
#      name: test scala-rsocket
#      script:
#        - cd $TRAVIS_BUILD_DIR/scala-rsocket && ./sbtw clean compile
#        - ( cd $TRAVIS_BUILD_DIR/scala-rsocket && ./sbtw "runMain com.github.daggerok.scalarsocket.Server" & )
#        - sleep 5s
#        - ./sbtw  "runMain com.github.daggerok.scalarsocket.Client"
#        - stop_any 7878
#    - stage: test
#      jdk: openjdk11
#      name: test scala-rsocket openjdk11
#      script: cd $TRAVIS_BUILD_DIR/scala-rsocket && ./sbtw clean compile ; (./sbtw "runMain com.github.daggerok.scalarsocket.Server" &) ; sleep 3s ; ./sbtw "runMain com.github.daggerok.scalarsocket.Client"
    - stage: test
      name: test es-rsocket maven
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/es-rsocket/es-server/src/main/resources/logback-maven.xml
                 $TRAVIS_BUILD_DIR/es-rsocket/es-server/src/main/resources/logback.xml
        - cp -Rf $TRAVIS_BUILD_DIR/es-rsocket/gateway-client/src/main/resources/logback-maven.xml
                 $TRAVIS_BUILD_DIR/es-rsocket/gateway-client/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f ./es-rsocket/pom.xml
        - java -jar $TRAVIS_BUILD_DIR/es-rsocket/es-server/target/*.jar &
        - wait_for 12345
        - java -jar $TRAVIS_BUILD_DIR/es-rsocket/gateway-client/target/*.jar &
        - wait_for 8080
        - http :8080/api/v1/add-command data:='{"trololo":"ololo","aggregateId":"83e24ff7-38fb-4d55-9399-9dbe5a926bd1"}' aggregateId=83e24ff7-38fb-4d55-9399-9dbe5a926bd1
        - http :8080/api/v1/add-command data:='{"trololo":"ololo","aggregateId":"83e24ff7-38fb-4d55-9399-9dbe5a926bd1"}' aggregateId=83e24ff7-38fb-4d55-9399-9dbe5a926bd1
        - http --stream :8080/api/v1/stream-commands/83e24ff7-38fb-4d55-9399-9dbe5a926bd1
        - stop_any 12345 8080 80
    - stage: test
      name: test es-rsocket gradle
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/es-rsocket/es-server/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/es-rsocket/es-server/src/main/resources/logback.xml
        - cp -Rf $TRAVIS_BUILD_DIR/es-rsocket/gateway-client/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/es-rsocket/gateway-client/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew -b ./es-rsocket/build.gradle.kts
        - java -jar $TRAVIS_BUILD_DIR/es-rsocket/es-server/build/libs/*.jar &
        - wait_for 12345
        - java -jar $TRAVIS_BUILD_DIR/es-rsocket/gateway-client/build/libs/*.jar &
        - wait_for 8080
        - http :8080/api/v1/add-command data:='{"trololo":"ololo","aggregateId":"83e24ff7-38fb-4d55-9399-9dbe5a926bd1"}' aggregateId=83e24ff7-38fb-4d55-9399-9dbe5a926bd1
        - http :8080/api/v1/add-command data:='{"trololo":"ololo","aggregateId":"83e24ff7-38fb-4d55-9399-9dbe5a926bd1"}' aggregateId=83e24ff7-38fb-4d55-9399-9dbe5a926bd1
        - http --stream :8080/api/v1/stream-commands/83e24ff7-38fb-4d55-9399-9dbe5a926bd1
        - stop_any 12345 8080 80
    - stage: test
      name: "Maven updates"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-maven.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -f ./spring-webflux-rsocker-example/pom.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -f ./rsocket-playground/pom.xml
    - stage: test
      name: "Gradle updates"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
        #- cd $TRAVIS_BUILD_DIR && ./gradlew --stop || echo 'oops...'
        - cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release -b spring-webflux-rsocker-example/build.gradle.kts --no-daemon
        - cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release -b rsocket-playground/build.gradle.kts
    - stage: test
      name: "Maven rsocker-java-example"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-maven.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -pl :rsocket-java-example package
        - java -jar rsocket-java-example/target/rsocket-java-example-*-SNAPSHOT-all.jar
    - stage: test
      name: "Gradle rsocker-java-example"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew rsocket-java-example:fatJar
        - java -jar rsocket-java-example/build/libs/rsocket-java-example-*-SNAPSHOT-all.jar
    - stage: test
      name: "Maven spring-webflux-rsocker-example"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-maven.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f ./spring-webflux-rsocker-example/pom.xml
        - java -jar ./spring-webflux-rsocker-example/rsocker-server/target/rsocker-server-*-SNAPSHOT.jar &
        - java -jar ./spring-webflux-rsocker-example/gateway-client/target/gateway-client-*-SNAPSHOT.jar &
        - wait_for 1234 8080
        - curl -sS 127.0.0.1:8080/api/v1/hello/max | jq '.'
        - stop_any 80 1234 8080
    - stage: test
      name: "Gradle spring-webflux-rsocker-example"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew -b spring-webflux-rsocker-example/build.gradle.kts
        - java -jar ./spring-webflux-rsocker-example/rsocker-server/build/libs/rsocker-server-*-SNAPSHOT.jar &
        - java -jar ./spring-webflux-rsocker-example/gateway-client/build/libs/gateway-client-*-SNAPSHOT.jar &
        - wait_for 1234 8080
        - curl -sS 127.0.0.1:8080/api/v1/hello/max | jq '.'
        - stop_any 80 1234 8080
    - stage: test
      name: "Maven rsocket-playground"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-maven.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw -pl :rsocket-playground
    - stage: test
      name: "Gradle rsocket-playground"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew -b ./rsocket-playground/build.gradle.kts

    # openjdk11
    - stage: test
      jdk: openjdk11
      name: "Maven rsocket-playground"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw -pl :rsocket-playground
    - stage: test
      name: "Gradle rsocket-playground"
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback-gradle.xml
                 $TRAVIS_BUILD_DIR/rsocket-playground/src/main/resources/logback.xml
        - cd $TRAVIS_BUILD_DIR && ./gradlew -b ./rsocket-playground/build.gradle.kts
before_cache:
  - find ~/.gradle -name '*.lock' -type f             -print0 | xargs -0 rm -v -rf '{}'
  - find ~/.gradle -name 'plugin-resolution' -type d  -print0 | xargs -0 rm -v -rf '{}'
cache:
  pip: true
  packages: true
  directories:
    - ~/.local/daggerok
    - ~/.gradle
    - ~/.sbt
    - ~/.ivy
    - ~/.m2
