notifications:
  email: false
git:
  quiet: true
  depth: 1
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
install: true
addons:
  apt:
    update: true
    packages:
      - jq
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - unzip
      - zip
before_install:
  # gradle
  - curl -s "https://get.sdkman.io" | bash
  - sed -i -e 's/^sdkman_auto_answer=false$/sdkman_auto_answer=true/g' "$HOME/.sdkman/etc/config"
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk use gradle 5.5-rc-2
  # wait_for / stop_any
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 1234 8080 5432
#before_script:
#  - ./gradlew --stop || echo 'oops...'
#  - killall -9 java || echo 'oops'
jobs:
  include:
    - stage: openjdk8
      jdk: openjdk8
      name: "Maven updates"
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -f ./spring-webflux-rsocker-example/pom.xml
        - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates -f ./rsocket-playground/pom.xml
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle updates"
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release
        #- cd $TRAVIS_BUILD_DIR && ./gradlew --stop || echo 'oops...'
        - cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release -b spring-webflux-rsocker-example/build.gradle.kts --no-daemon
        - cd $TRAVIS_BUILD_DIR && ./gradlew dependencyUpdates -Drevision=release -b rsocket-playground/build.gradle.kts
    - stage: openjdk8
      jdk: openjdk8
      name: "Maven rsocker-java-example"
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -pl :rsocket-java-example package
        - java -jar rsocket-java-example/target/rsocket-java-example-*-SNAPSHOT-all.jar
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle rsocker-java-example"
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew rsocket-java-example:fatJar
        - java -jar rsocket-java-example/build/libs/rsocket-java-example-*-SNAPSHOT-all.jar
    - stage: openjdk8
      jdk: openjdk8
      name: "Maven spring-webflux-rsocker-example"
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw -f ./spring-webflux-rsocker-example/pom.xml
        - java -jar ./spring-webflux-rsocker-example/rsocker-server/target/rsocker-server-*-SNAPSHOT.jar &
        - java -jar ./spring-webflux-rsocker-example/gateway-client/target/gateway-client-*-SNAPSHOT.jar &
        - wait_for 1234 8080
        - curl -sS 127.0.0.1:8080/api/v1/hello/max | jq '.'
        - stop_any 80 1234 8080
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle spring-webflux-rsocker-example"
      script:
        - cd $TRAVIS_BUILD_DIR && ./gradlew -b spring-webflux-rsocker-example/build.gradle.kts
        - java -jar ./spring-webflux-rsocker-example/rsocker-server/build/libs/rsocker-server-*-SNAPSHOT.jar &
        - java -jar ./spring-webflux-rsocker-example/gateway-client/build/libs/gateway-client-*-SNAPSHOT.jar &
        - wait_for 1234 8080
        - curl -sS 127.0.0.1:8080/api/v1/hello/max | jq '.'
        - stop_any 80 1234 8080
    - stage: openjdk8
      jdk: openjdk8
      name: "Maven rsocket-playground"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw -pl :rsocket-playground
    - stage: openjdk8
      jdk: openjdk8
      name: "Gradle rsocket-playground"
      script: cd $TRAVIS_BUILD_DIR && ./gradlew -b ./rsocket-playground/build.gradle.kts

    # openjdk11
    - stage: openjdk11
      jdk: openjdk11
      name: "Maven rsocket-playground"
      script: cd $TRAVIS_BUILD_DIR && ./mvnw -pl :rsocket-playground
    - stage: openjdk11
      jdk: openjdk11
      name: "Gradle rsocket-playground"
      script: cd $TRAVIS_BUILD_DIR && ./gradlew -b ./rsocket-playground/build.gradle.kts
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
